// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: protos/mcbeam.proto

package mcbeamproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for McbApp service

func NewMcbAppEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for McbApp service

type McbAppService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Push(ctx context.Context, in *PushMsg, opts ...client.CallOption) (*Response, error)
	Bind(ctx context.Context, in *BindMsg, opts ...client.CallOption) (*Response, error)
	Kick(ctx context.Context, in *KickMsg, opts ...client.CallOption) (*KickAnswer, error)
}

type mcbAppService struct {
	c    client.Client
	name string
}

func NewMcbAppService(name string, c client.Client) McbAppService {
	return &mcbAppService{
		c:    c,
		name: name,
	}
}

func (c *mcbAppService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "McbApp.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcbAppService) Push(ctx context.Context, in *PushMsg, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "McbApp.Push", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcbAppService) Bind(ctx context.Context, in *BindMsg, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "McbApp.Bind", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcbAppService) Kick(ctx context.Context, in *KickMsg, opts ...client.CallOption) (*KickAnswer, error) {
	req := c.c.NewRequest(c.name, "McbApp.Kick", in)
	out := new(KickAnswer)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for McbApp service

type McbAppHandler interface {
	Call(context.Context, *Request, *Response) error
	Push(context.Context, *PushMsg, *Response) error
	Bind(context.Context, *BindMsg, *Response) error
	Kick(context.Context, *KickMsg, *KickAnswer) error
}

func RegisterMcbAppHandler(s server.Server, hdlr McbAppHandler, opts ...server.HandlerOption) error {
	type mcbApp interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Push(ctx context.Context, in *PushMsg, out *Response) error
		Bind(ctx context.Context, in *BindMsg, out *Response) error
		Kick(ctx context.Context, in *KickMsg, out *KickAnswer) error
	}
	type McbApp struct {
		mcbApp
	}
	h := &mcbAppHandler{hdlr}
	return s.Handle(s.NewHandler(&McbApp{h}, opts...))
}

type mcbAppHandler struct {
	McbAppHandler
}

func (h *mcbAppHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.McbAppHandler.Call(ctx, in, out)
}

func (h *mcbAppHandler) Push(ctx context.Context, in *PushMsg, out *Response) error {
	return h.McbAppHandler.Push(ctx, in, out)
}

func (h *mcbAppHandler) Bind(ctx context.Context, in *BindMsg, out *Response) error {
	return h.McbAppHandler.Bind(ctx, in, out)
}

func (h *mcbAppHandler) Kick(ctx context.Context, in *KickMsg, out *KickAnswer) error {
	return h.McbAppHandler.Kick(ctx, in, out)
}
